### ISSUE TITLE
heartbeat_interval parameter makes tests/test_tumblesle_release.py to fail

### ISSUE THREAD

**Issue by b10n1k** [os-autoinst/openqa_review#120]
test_notifications_are_sent is failing when tox is executed for openqa_review. In this particular test pika.BlockingConnection is used. Example of the failure can be found on https://travis-ci.org/os-autoinst/openqa_review/jobs/514592861. The problem seems to arise from the pika version for both python2 and python3.

**Comment by okurz** [comment]
https://github.com/os-autoinst/openqa_review/commit/853d57af1ea9bba78d32288b1f5a16eb89212143
