### ISSUE TITLE
Network-settings

### ISSUE THREAD

**Issue by FabianEn** [os-autoinst/openqa_review#122]
Hello,

i am trying to create a test with openQA and connect to network.
For example start machine and ping an adress (www.google.com) . But i cant find a way to give the openQA machine an ip-address. Do i have to use openvswitch ? Or os-autoinst-openvswitch ? Is there a guide for networking that could help me ?
Thanks a lot. Fabi

**Comment by okurz** [comment]
Meanwhile we have talked over different communication channels :) http://open.qa/docs/#networking is the official upstream documentation for that. The github project for openQA itself would be http://github.com/os-autoinst/openQA/
